crm/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', 'Controller@redirectTo')->name('home')->middleware('auth');
Route::get('/home', 'Controller@redirectTo')->name('home')->middleware('auth');
Route::get('/index', 'Controller@redirectTo')->name('home')->middleware('auth');

Route::get('/admin/profile', 'HomeController@index_admin')->name('profile_admin')->middleware('auth');
Route::get('/admin/dashboard', 'DashboardController@index')->name('dashboard_admin')->middleware('auth');
Route::get('/admin/cliente', 'CustomerController@index')->name('cliente_admin')->middleware('auth');
Route::get('/admin/cliente_ext', 'CustomerController@index_ext')->name('cliente_admin')->middleware('auth');
Route::get('/admin/cerca_privato', 'CustomersController@search_privato')->name('search_privato')->middleware('auth');
Route::get('/admin/cerca_azienda', 'CustomersController@search_privato_ext')->name('search_privato_ext')->middleware('auth');
Route::get('/admin/cerca_adv', 'AdvController@search_adv')->name('search_adv')->middleware('auth');
Route::get('/admin/cerca_advext', 'AdvController@search_adv_ext')->name('search_adv_ext')->middleware('auth');

Route::get('/admin/cliente/{id}', 'CustomerController@edit')->name('cliente_profile_admin')->middleware('auth');
Route::get('/admin/customerUpdate/{id}', 'CustomerController@update')->name('customerUpdate')->middleware('auth');

Route::get('/admin/adv', 'AdvController@index')->name('adv_admin')->middleware('auth');
Route::get('/admin/adv_ext', 'AdvController@index_ext')->name('adv_admin_ext')->middleware('auth');
Route::get('/admin/adv/{id}', 'AdvController@show')->name('adv_profile_admin')->middleware('auth');
Route::get('/admin/adv/edit/{id}', 'AdvController@edit')->name('adv_profile_edit_admin')->middleware('auth');

Route::get('/admin/clienti', 'CustomersController@index')->name('clienti_admin')->middleware('auth');
Route::get('/admin/clienti/categories', 'CategoryCustomersController@index')->name('categories_customers.index')->middleware('auth');
Route::post('/admin/clienti/category/store', 'CategoryCustomersController@store')->name('category_customers.store')->middleware('auth');
Route::get('/admin/clienti/category', 'CategoryCustomersController@create')->name('category_customers.new')->middleware('auth');
Route::get('/admin/clienti/category/{id}', 'CategoryCustomersController@create')->name('category_customers.edit')->middleware('auth');
Route::get('/admin/clienti/category/{id}/delete', 'CategoryCustomersController@delete')->name('category_customers.delete')->middleware('auth');
Route::get('/admin/preventivi', 'PreventivoController@index')->name('preventivi')->middleware('auth');
Route::get('/admin/preventivo', 'PreventivoController@create')->name('preventivo')->middleware('auth');
Route::get('/admin/preventivo/edit/{id}', 'PreventivoController@edit')->name('preventivo')->middleware('auth');

Route::post('/admin/preventivo/topdf/{id}', 'PreventivoController@topdf')->name('preventivo')->middleware('auth');
Route::get('/admin/preventivo/getpdf/{name}', 'PreventivoController@getpdf')->name('preventivo')->middleware('auth');

Route::get('/admin/aziende', 'CustomersController@index_ext')->name('clienti_admin_ext')->middleware('auth');
Route::get('/admin/travel', 'TravelController@index')->name('travel_admin')->middleware('auth');

Route::get('/admin/tasks', 'TaskController@index')->name('tasks_admin')->middleware('auth');
Route::get('/admin/news', 'NewsController@index')->name('news_admin')->middleware('auth');
Route::get('/admin/newUser', 'newUserController@index')->name('new_user')->middleware('auth');
Route::get('/admin/reparti', 'RepartiController@index')->name('reparti')->middleware('auth');

Route::get('/admin/newUser/{id}', 'newUserController@edit')->name('edituser')->middleware('auth');
Route::get('/admin/newUser2', 'newUserController@storeedit')->name('storeedit')->middleware('auth');
Route::get('/admin/reparti/store', 'RepartiController@store')->name('repartoStore')->middleware('auth');
Route::get('/admin/reparti/{id}', 'RepartiController@edit')->name('repartoEdit')->middleware('auth');

Route::get('/admin/preventiviSearch', 'PreventivoController@preventiviSearch')->name('preventiviSearch')->middleware('auth');

Route::get('/admin/uploads', 'uploadsController@index')->name('uploads')->middleware('auth');
Route::post('/admin/uploads', 'uploadsController@store')->name('uploadsStore')->middleware('auth');

Route::get('/admin/settings', 'uploadsController@index_settings')->name('index_settings')->middleware('auth');
Route::post('/admin/settings', 'uploadsController@update_settings')->name('update_settings')->middleware('auth');

Route::get('/user/business', 'BusinessController@index')->name('newbusiness')->middleware('auth');
Route::get('/user/business/{id}', 'BusinessController@edit')->name('editbusiness')->middleware('auth');

Route::get('/user/profile', 'HomeController@index_user')->name('profile_user')->middleware('auth');
Route::get('/user/dashboard', 'DashboardController@index')->name('dashboard_user')->middleware('auth');
Route::get('/test', 'DashboardController@test')->name('test')->middleware('auth');
Route::get('/user/cliente', 'CustomerController@index')->name('cliente_user');
Route::get('/user/cliente/{id}', 'CustomerController@show')->name('cliente_profile_user');
Route::get('/user/cliente/edit/{id}', 'CustomerController@edit')->name('cliente_profile_edit_user');


Route::get('/user/adv', 'AdvController@index')->name('adv_user')->middleware('auth');
Route::get('/user/adv_ext', 'AdvController@index_ext')->name('adv_user_ext')->middleware('auth');
Route::get('/user/adv/{id}', 'AdvController@show')->name('adv_profile_user')->middleware('auth');
Route::get('/user/adv/edit/{id}', 'AdvController@edit')->name('adv_profile_edit_user')->middleware('auth');
Route::get('/user/new', 'AdvController@newadv')->name('newadv')->middleware('auth');
Route::get('/user/new_ext', 'AdvController@newadv_ext')->name('newadv_ext')->middleware('auth');

Route::get('/user/clienti', 'CustomersController@index')->name('clienti_user')->middleware('auth');
Route::get('/user/clienti_ext', 'CustomersController@index_ext')->name('clienti_user_ext')->middleware('auth');
Route::get('/user/tasks', 'TaskController@index')->name('tasks_user')->middleware('auth');
Route::get('/user/travel', 'TravelController@index')->name('travel_user')->middleware('auth');
Route::get('/user/news', 'NewsController@index')->name('news_user')->middleware('auth');
Route::get('/user/news/{id}', 'NewsController@edit')->name('editnews')->middleware('auth');

Route::get('/clienti-data', 'CustomersController@data')->name('clienti_data')->middleware('auth');
Route::get('/clienti-data_ext', 'CustomersController@data_ext')->name('clienti_data_ext')->middleware('auth');

Route::get('/user-data', 'newUserController@data')->name('user_data')->middleware('auth');
Route::get('/clienti-adv-data', 'AdvController@data')->name('clienti_adv_data')->middleware('auth');
Route::get('/clienti-adv-data2', 'AdvController@data_ext')->name('clienti_adv_data_ext')->middleware('auth');

Route::get('/travels-data/{customer_id}', 'TravelController@getTravelByCustomerId')->name('travels_data')->middleware('auth');
Route::get('/files-data/{customer_id}', 'FilesController@data')->name('files_data')->middleware('auth');
Route::get('/file/delete/{id_file}', 'FileController@logicDelete')->name('delete_file')->middleware('auth');

Route::get('/news-data', 'NewsController@data')->name('news_data')->middleware('auth');
Route::get('/task/marked/{id}', 'TaskController@logicDelete')->name('task_marked')->middleware('auth');
Route::get('/news/read/{id}', 'NewsController@readNews')->name('read_news')->middleware('auth');


Route::get('/admin/cards', 'CardController@index')->name('cards')->middleware('auth');
Route::get('/admin/card/new', 'CardController@create')->name('cards new')->middleware('auth');
Route::get('/admin/card/edit/{id}', 'CardController@edit')->name('card edit')->middleware('auth');
Route::post('/admin/cards/duplify', 'CardController@copy')->name('copycards')->middleware('auth');

Route::get('/admin/coupon', 'CouponController@index')->name('coupon')->middleware('auth');
Route::get('/admin/coupon/new', 'CouponController@create')->name('coupon new')->middleware('auth');
Route::get('/admin/coupon/edit/{id}', 'CouponController@edit')->name('coupon edit')->middleware('auth');
Route::post('/admin/coupon/duplify', 'CouponController@copy')->name('copycoupon')->middleware('auth');

Route::get('/autocomplete', 'ComuniController@autocomplete')->name('autocomplete')->middleware('auth');
Route::get('/autocomplete_ext', 'ComuniController@autocomplete_ext')->name('autocomplete_ext')->middleware('auth');
Route::post('/task/mail/', 'TaskController@sendMail')->name('send-mail')->middleware('auth');

Route::resource('preventivo', 'PreventivoController');
Route::resource('card', 'CardController');
Route::resource('coupon', 'CouponController');
Route::resource('customer', 'CustomerController');
Route::resource('customers', 'CustomersController');
Route::resource('customer_adv', 'AdvController');
Route::resource('newUser', 'newUserController');
Route::resource('uploads', 'uploadsController');
Route::resource('travel', 'TravelController');
Route::resource('tasks', 'TaskController');
Route::resource('news', 'NewsController');
Route::resource('file', 'FileController');
Route::resource('reparti', 'RepartiController');
Route::resource('business', 'BusinessController');

crm/resources/views/admin/news.blade.php
@extends('layouts.master')
@section('header-page-personalization')
    <style>
        #news_table thead,
        #news_table th {text-align: center;background: #61b1c1!important;}
        #news_table tr {text-align: center;}
        .disabled {
            pointer-events: none;
            cursor: default;
        }

    </style>
@endsection
@section('content')

    <div class="page_content page_news col-lg-6 pull-left">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <form id="login_form" role="form" method="POST" action="{{ route('news.store') }}">
                        {{ csrf_field() }}
                        <div class="panel panel-default">

                            <div class="panel-body">
                                <fieldset>
                                    <legend><span class="big-title">News</span></legend>
                                </fieldset>
                                @if(session()->has('message'))
                                    <div class="alert alert-success">
                                        {{ session()->get('message') }}
                                    </div>
                                @endif
                                @if(session()->has('error'))
                                    <div class="alert alert-error">
                                        {{ session()->get('error') }}
                                    </div>
                                @endif
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            <label for="reg_input">Titolo News</label>
                                            <input type="text" id="news_title" name="news_title" class="form-control">
                                        </div>
                                    </div>
                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            <label for="evidenza_news">In evidenza?</label>
                                            	<select id="evidenza_news" name="evidenza_news" class="form-control" onchange="evidenzadeadline(this.value)">
		                                            <option value="0" selected>No</option>
		                                            <option value="1">Si</option>
	                                            </select>
                                        </div>
                                    </div>
                                    <div class="form-group col-lg-12">
                                        <label for="evidenza_news">In evidenza fino al</label>
                                        <input disabled="" type="date" id="evidenzadeadline" name="evidenzadeadline" class="form-control" style="text-transform: uppercase;">
                                    </div>
                                    <div class="form-group col-lg-12">
                                        <label for="evidenza_news">Visibile fino al</label>
                                        <input type="date" id="deadline" name="deadline" class="form-control" style="text-transform: uppercase;">
                                    </div>
                                </div>

                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            <label for="reg_input">Zona News - Scegli la zona in cui sarà visualizzata la News</label>
                                            <select id="zone" name="zone" class="form-control">
                                            <option disabled>Scegli una zona</option>
                                            <?php
                                                $zone=DB::select("SELECT * FROM `newsZone`");
                                                for($i=0;$i<count($zone);$i++){?>
                                                <option value="{{$zone[$i]->zone}}">{{$zone[$i]->zone}}</option>
                                            <?php } ?>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-lg-12">
                                        <div class="">
                                            <!--<div class="panel-heading"></div>-->
                                            <div class="panel_body_a">
            									<textarea name="wysiwg_full" id="wysiwg_full" cols="30" rows="4" class="form-control">

            									</textarea>
                                            </div>
                                        </div>
                                    </div>
                            </div>
                            <button class="btn btn-lg btn-success btn-block confirmsave">Salva</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="page_content pagelist main-temporaneo col-lg-6 pull-left" style="margin-left: 0px;">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <fieldset>
                                <legend><span class="big-title">Elenco News</span></legend>
                            </fieldset>

                            <div class="row">
                                <div class="col-lg-12">
                                    <table class="table table-bordered table-striped" id="news_table">
                                        <thead>
                                        <tr>
                                            <th>Id</th>
                                            <th>Titolo News</th>
                                            <th>Visibilità</th>
                                            <th>Data Creazione</th>
                                            <th style="width: 90px;">Azioni</th>
                                        </tr>
                                        </thead>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="modal_news_file">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body">
                   <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h3>Titolo News</h3>

                        <div class="">
                            <div class="">
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            <label for="reg_input">Testo News</label>
                                            <h4></h4>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                </div>
            </div>
        </div>
    </div>


@endsection
@section('footer-plugin')
    <!-- wysiwg editor -->
    <script src="{{ asset('/lib/ckeditor/ckeditor.js') }}"></script>
    <script src="{{ asset('/lib/ckeditor/adapters/jquery.js') }}"></script>
    <!-- wizard functions -->
    <script src="{{ asset('/js/apps/tisa_wysiwg.js') }}"></script>
    <!-- datatables -->
    <script src="{{ asset('/lib/DataTables/media/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('/lib/DataTables/media/js/dataTables.bootstrap.js') }}"></script>
    <script src="{{ asset('/lib/DataTables/extensions/TableTools/js/dataTables.tableTools.min.js') }}"></script>
    <script src="{{ asset('/lib/DataTables/extensions/Scroller/js/dataTables.scroller.min.js') }}"></script>

    <!-- datatables functions -->
    <script src="{{ asset('/js/apps/tisa_datatables.js') }}"></script>

    <script>
    $('#evidenza_news').change(function(){
      if (this.value=='1')
      $('#evidenzadeadline').prop('disabled',false)
      else
      $('#evidenzadeadline').prop('disabled',true)
      })

        $('#news_table').DataTable({
            processing: true,
            serverSide: true,
            ajax: '{!! route('news_data') !!}',
            "ordering": false,
            columns: [
                {data: 'id'},
                {data: 'news_title'},
                {data: 'evidenza'},
                {data: 'created_at'},
                {data: 'azioni'}
            ],oLanguage: {sSearch: "Filtra: "},
            "aoColumnDefs": [
                {
                    "bSearchable": true,
                    "bVisible": true,
                    "aTargets": [ 0 ]
                },
                {
                    "bSearchable": true,
                    "bVisible": true,
                    "aTargets": [ 1 ]
                },
                {
                    "bSearchable": true,
                    "bVisible": true,
                    "aTargets": [ 2 ]
                },
                {
                    "bSearchable": true,
                    "bVisible": true,
                    "aTargets": [ 3 ]
                },
                {
                    "bSearchable": false,
                    "bVisible": true,
                    "aTargets": [ 4 ]
                }
            ]
        });

        $("table:eq(0) th:last").removeClass("sorting");

        window['table']="news";

    function loadnews(id){

        $.post(apiUrl+'api.php',{qr:'loadnews',id:id},function(response){
            response=JSON.parse(response);
            response=response[0];
            $("#news_title").val(response.news_title);

            if(response.breaking==1)
                $("#evidenza_news option[value='2']").prop("selected",true);
            else
                $("#evidenza_news option[value='"+response.evidenza+"']").prop("selected",true);

            $("#zone option[value='"+response.zone+"']").prop("selected",true);
            $("#deadline").val(response.deadline);
            CKEDITOR.instances.wysiwg_full.setData(response.news_body);
            if($("#idn").length==0)
                $("form").append("<input type='hidden' name='id' id='idn' value='"+response.id+"'>");
            else
               $("#idn").val(response.id);
        })
    }

    function evidenzadeadline(i){
        if(i=="1")
            $("#evidenzadeadline").prop("disabled",true);
        else
            $("#evidenzadeadline").prop("disabled",false);
    }

    </script>
@endsection

crm/resources/views/admin/reparti.blade.php
@extends('layouts.master')
@section('header-page-personalization')
    <style>
        .twitter-typeahead, .tt-hint, .tt-input, .tt-menu { width: 100%;  }
        .tt-menu {
            background: #ffffff;
        }
  button.accordion {
    background-color: #eee;
    color: #444;
    cursor: pointer;
    padding: 18px;
    width: 100%;
    border: none;
    text-align: left;
    outline: none;
    font-size: 15px;
    transition: 0.4s;
}

button.accordion.active, button.accordion:hover {
    background-color: #ddd;
}

button.accordion:after {
    content: '\002B';
    color: #777;
    font-weight: bold;
    float: right;
    margin-left: 5px;
}

button.accordion.active:after {
    content: "\2212";
}

div.panelacc {
    padding: 0 18px;
    background-color: white;
    max-height: 0;
    overflow: hidden;
    transition: max-height 0.2s ease-out;
}      
    </style>
@endsection
@section('content')

    <div class="page_content page_reparti">
        <div class="container-fluid">
                           @if(session()->has('message'))
                                <div class="alert alert-success">
                                    {{ session()->get('message') }}
                                </div>
                            @endif         
            <div class="row">
                <div class="col-lg-12">
                  <div class="panel panel-default">
                            <div class="panel-body">
                  <form id="register_form" role="form" method="POST" action="{{route('reparti.store')}}">
                      {{ csrf_field() }}
                      <h1 class="login_heading"><legend><span class="big-title">Crea un Nuovo reparto</span></legend></h1>
                      <div class="form-group">
                          <label for="register_username">Nome reparto</label>
                          <input type="hidden" name="id" value="<?php if(isset($reparto)&&isset($reparto['id'])&&!empty($reparto['id'])) echo $reparto['id']; else echo '-1'; ?>">
                          <input type="text" class="form-control input-lg" name="name" id="name" value="<?php if(isset($reparto)&&isset($reparto['reparti'])&&!empty($reparto['reparti'])) echo $reparto['reparti'] ?>" required
                                 autofocus>
                      </div>

                      <div class="submit_section">
                          <button type="submit" class="btn btn-lg btn-success btn-block">Salva</button>

                      </div>
                  </form>
                </div>
              </div>
                </div>

            </div>
        </div>
<br>

        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                        <div class="panel panel-default">

                            <div class="panel-body">
                                <fieldset>
                                    <legend><span class="big-title">Reparti</span></legend>
                                    <p>Gestisci i reparti della piattaforma</p>
                                </fieldset>
                                <div class="row">
                                    <div class="col-lg-12">



      <table class="table table-bordered" id="user_table" >
        <thead>

          <tr>
            <th>Descrizione</th>
            <th>Ultima modifica</th>
            <th>Modifica</th>
            <th>Elimina</th>
          </tr>

        </thead>

        <tbody>

        @foreach ($reparti as $reparto)
          <tr>
            <td style="display: none;">{{$reparto->id}}</td>
            <td>{{$reparto->reparti}}</td>
            <td>{{$reparto->updated_at}}</td>
            <?php if($reparto->id!=1){ ?>
            <?php if(isset($isedit)){ ?>
              <td><a href="{{$reparto->id}}" class="btn btn-xs btn-secondary"><i class="glyphicon glyphicon-edit"></i>&nbsp;Modifica</a></td>
            <?php }else { ?>
              <td><a href="reparti/{{$reparto->id}}" class="btn btn-xs btn-secondary"><i class="glyphicon glyphicon-edit"></i>&nbsp;Modifica</a></td>
            <?php } ?>
              <td><a href="#" class="btn btn-xs btn-danger news-zama" style="margin-left: 10px;" onclick="deleteRecord(this)"><i class="glyphicon glyphicon-minus" class="disabled"></i>&nbsp;Elimina</a></td>
            <?php }else { ?>
              <td><p>Non è possibile modificare questo gruppo</p></td>
              <td><p>Non è possibile eliminare questo gruppo</p></td>
            <?php } ?>
          </tr>
        @endforeach

        </tbody>

      </table>

                                    </div>
                                </div>
</div>
</div>
<br>
                                <div class="row">
                                    <div class="col-lg-12">
<style type="text/css">
  #lost th, #lost td{
    width: 150px;
    text-align: center;
  }
</style>
      <div class="row">
        <div class="col-lg-12">
          <div class="panel panel-default">
                            <div class="panel-body">
        <h1><legend><span class="big-title">Appartenenza degli utenti ai reparti</span></legend></h1>
        <?php 
          if(!isset($utentiIngruppo))
            $utentiIngruppo=[];
          $utentiIngruppoFormattati=[];
          for($i=0;$i<count($utentiIngruppo);$i++)
              $utentiIngruppoFormattati[$utentiIngruppo[$i]->repId]=explode(",", $utentiIngruppo[$i]->userIdList);

        

        ?>
        @foreach ($reparti as $reparto)

          <div class="fkacc col-lg-6"> 
                                                    <a class="accordion col-md-12"><i class="fa fa-plus" aria-hidden="true"></i>
                                                      {{$reparto->reparti}} <span>(<?php if(isset($utentiIngruppoFormattati[$reparto->id])) echo count($utentiIngruppoFormattati[$reparto->id]); else echo "0 Utenti"; ?>
        <?php if(isset($utentiIngruppoFormattati[$reparto->id])&&count($utentiIngruppoFormattati[$reparto->id])!=1) echo "Utenti"; else echo "Utente"; ?>
        )</span></a>
                                                    <div class="panel accordion-contenuto col-lg-12">
                                                      <div class="panel-body">
                                                      <table id="lost" class="col-lg-12">
                                                      <thead>
                                                        <th>Nome utente</th>
                                                        <th>Appartiene a questo gruppo?</th>
                                                      </thead>
                                                        <tbody>
                                                          @foreach ($allusers as $user)
                                                          <tr>

                                                            <td>{{$user->name}}</td>
                                                            <?php if(isset($utentiIngruppoFormattati[$reparto->id])&&in_array($user->id, $utentiIngruppoFormattati[$reparto->id])){ ?>
                                                              <td><input type="checkbox" name="isInGroup" data-userid="{{$user->id}}" data-group="{{$reparto->id}}" checked onclick="removeGroup(this)"></td>
                                                            <?php }else{ ?>
                                                            <td><input type="checkbox" name="isInGroup" data-userid="{{$user->id}}" data-group="{{$reparto->id}}" onclick="addGroup(this)"></td>
                                                            <?php } ?>

                                                          </tr>
                                                           @endforeach
                                                        </tbody>
                                                      </table>
                                                    </div>
                                                    </div>
                                                </div>


          @endforeach
        </div>
      </div>
        </div>
      </div>
  </div>
</div>



<script>
/*
var acc = document.getElementsByClassName("accordion");
var i;

for (i = 0; i < acc.length; i++) {
  acc[i].onclick = function() {
    this.classList.toggle("active");
    var panel = this.nextElementSibling;
    if (panel.style.maxHeight){
      panel.style.maxHeight = null;
    } else {
      panel.style.maxHeight = panel.scrollHeight + "px";
    } 
  }
}*/
</script>

                            </div>
                        </div>
                </div>
            </div>
        </div>

    </div>
@endsection
@section('footer-plugin')
<script type="text/javascript">
  window['table']="reparti";


var apiUrl="/";
function addGroup(el){
  var data=$(el).data();

  $.ajax({
         url: apiUrl+'api.php',        
         type: "POST",
         data: { qr:'addGroup', userid:data.userid,group:data.group},
         success: function(res){
        debugger;
    },
    error: function(){
      console.log("ajax error ");

    }
  });   
}

function removeGroup(el){
  var data=$(el).data();

  $.ajax({
         url: apiUrl+'api.php',        
         type: "POST",
         data: { qr:'removeGroup', userid:data.userid,group:data.group},
         success: function(res){
        debugger;
    },
    error: function(){
      console.log("ajax error ");

    }
  });   
}

</script>
@endsection