crm/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', 'Controller@redirectTo')->name('home')->middleware('auth');
Route::get('/home', 'Controller@redirectTo')->name('home')->middleware('auth');
Route::get('/index', 'Controller@redirectTo')->name('home')->middleware('auth');

Route::get('/admin/profile', 'HomeController@index_admin')->name('profile_admin')->middleware('auth');
Route::get('/admin/dashboard', 'DashboardController@index')->name('dashboard_admin')->middleware('auth');
Route::get('/admin/cliente', 'CustomerController@index')->name('cliente_admin')->middleware('auth');
Route::get('/admin/cliente_ext', 'CustomerController@index_ext')->name('cliente_admin')->middleware('auth');
Route::get('/admin/cerca_privato', 'CustomersController@search_privato')->name('search_privato')->middleware('auth');
Route::get('/admin/cerca_azienda', 'CustomersController@search_privato_ext')->name('search_privato_ext')->middleware('auth');
Route::get('/admin/cerca_adv', 'AdvController@search_adv')->name('search_adv')->middleware('auth');
Route::get('/admin/cerca_advext', 'AdvController@search_adv_ext')->name('search_adv_ext')->middleware('auth');

Route::get('/admin/cliente/{id}', 'CustomerController@edit')->name('cliente_profile_admin')->middleware('auth');
Route::get('/admin/customerUpdate/{id}', 'CustomerController@update')->name('customerUpdate')->middleware('auth');

Route::get('/admin/adv', 'AdvController@index')->name('adv_admin')->middleware('auth');
Route::get('/admin/adv_ext', 'AdvController@index_ext')->name('adv_admin_ext')->middleware('auth');
Route::get('/admin/adv/{id}', 'AdvController@show')->name('adv_profile_admin')->middleware('auth');
Route::get('/admin/adv/edit/{id}', 'AdvController@edit')->name('adv_profile_edit_admin')->middleware('auth');

Route::get('/admin/clienti', 'CustomersController@index')->name('clienti_admin')->middleware('auth');
Route::get('/admin/clienti/categories', 'CategoryCustomersController@index')->name('categories_customers.index')->middleware('auth');
Route::post('/admin/clienti/category/store', 'CategoryCustomersController@store')->name('category_customers.store')->middleware('auth');
Route::get('/admin/clienti/category', 'CategoryCustomersController@create')->name('category_customers.new')->middleware('auth');
Route::get('/admin/clienti/category/{id}', 'CategoryCustomersController@create')->name('category_customers.edit')->middleware('auth');
Route::get('/admin/clienti/category/{id}/delete', 'CategoryCustomersController@delete')->name('category_customers.delete')->middleware('auth');
Route::get('/admin/preventivi', 'PreventivoController@index')->name('preventivi')->middleware('auth');
Route::get('/admin/preventivo', 'PreventivoController@create')->name('preventivo')->middleware('auth');
Route::get('/admin/preventivo/edit/{id}', 'PreventivoController@edit')->name('preventivo')->middleware('auth');

Route::post('/admin/preventivo/topdf/{id}', 'PreventivoController@topdf')->name('preventivo')->middleware('auth');
Route::get('/admin/preventivo/getpdf/{name}', 'PreventivoController@getpdf')->name('preventivo')->middleware('auth');

Route::get('/admin/aziende', 'CustomersController@index_ext')->name('clienti_admin_ext')->middleware('auth');
Route::get('/admin/travel', 'TravelController@index')->name('travel_admin')->middleware('auth');

Route::get('/admin/tasks', 'TaskController@index')->name('tasks_admin')->middleware('auth');
Route::get('/admin/news', 'NewsController@index')->name('news_admin')->middleware('auth');
Route::get('/admin/newUser', 'newUserController@index')->name('new_user')->middleware('auth');
Route::get('/admin/reparti', 'RepartiController@index')->name('reparti')->middleware('auth');

Route::get('/admin/newUser/{id}', 'newUserController@edit')->name('edituser')->middleware('auth');
Route::get('/admin/newUser2', 'newUserController@storeedit')->name('storeedit')->middleware('auth');
Route::get('/admin/reparti/store', 'RepartiController@store')->name('repartoStore')->middleware('auth');
Route::get('/admin/reparti/{id}', 'RepartiController@edit')->name('repartoEdit')->middleware('auth');

Route::get('/admin/preventiviSearch', 'PreventivoController@preventiviSearch')->name('preventiviSearch')->middleware('auth');

Route::get('/admin/uploads', 'uploadsController@index')->name('uploads')->middleware('auth');
Route::post('/admin/uploads', 'uploadsController@store')->name('uploadsStore')->middleware('auth');

Route::get('/admin/settings', 'uploadsController@index_settings')->name('index_settings')->middleware('auth');
Route::post('/admin/settings', 'uploadsController@update_settings')->name('update_settings')->middleware('auth');

Route::get('/user/business', 'BusinessController@index')->name('newbusiness')->middleware('auth');
Route::get('/user/business/{id}', 'BusinessController@edit')->name('editbusiness')->middleware('auth');

Route::get('/user/profile', 'HomeController@index_user')->name('profile_user')->middleware('auth');
Route::get('/user/dashboard', 'DashboardController@index')->name('dashboard_user')->middleware('auth');
Route::get('/test', 'DashboardController@test')->name('test')->middleware('auth');
Route::get('/user/cliente', 'CustomerController@index')->name('cliente_user');
Route::get('/user/cliente/{id}', 'CustomerController@show')->name('cliente_profile_user');
Route::get('/user/cliente/edit/{id}', 'CustomerController@edit')->name('cliente_profile_edit_user');


Route::get('/user/adv', 'AdvController@index')->name('adv_user')->middleware('auth');
Route::get('/user/adv_ext', 'AdvController@index_ext')->name('adv_user_ext')->middleware('auth');
Route::get('/user/adv/{id}', 'AdvController@show')->name('adv_profile_user')->middleware('auth');
Route::get('/user/adv/edit/{id}', 'AdvController@edit')->name('adv_profile_edit_user')->middleware('auth');
Route::get('/user/new', 'AdvController@newadv')->name('newadv')->middleware('auth');
Route::get('/user/new_ext', 'AdvController@newadv_ext')->name('newadv_ext')->middleware('auth');

Route::get('/user/clienti', 'CustomersController@index')->name('clienti_user')->middleware('auth');
Route::get('/user/clienti_ext', 'CustomersController@index_ext')->name('clienti_user_ext')->middleware('auth');
Route::get('/user/tasks', 'TaskController@index')->name('tasks_user')->middleware('auth');
Route::get('/user/travel', 'TravelController@index')->name('travel_user')->middleware('auth');
Route::get('/user/news', 'NewsController@index')->name('news_user')->middleware('auth');
Route::get('/user/news/{id}', 'NewsController@edit')->name('editnews')->middleware('auth');

Route::get('/clienti-data', 'CustomersController@data')->name('clienti_data')->middleware('auth');
Route::get('/clienti-data_ext', 'CustomersController@data_ext')->name('clienti_data_ext')->middleware('auth');

Route::get('/user-data', 'newUserController@data')->name('user_data')->middleware('auth');
Route::get('/clienti-adv-data', 'AdvController@data')->name('clienti_adv_data')->middleware('auth');
Route::get('/clienti-adv-data2', 'AdvController@data_ext')->name('clienti_adv_data_ext')->middleware('auth');

Route::get('/travels-data/{customer_id}', 'TravelController@getTravelByCustomerId')->name('travels_data')->middleware('auth');
Route::get('/files-data/{customer_id}', 'FilesController@data')->name('files_data')->middleware('auth');
Route::get('/file/delete/{id_file}', 'FileController@logicDelete')->name('delete_file')->middleware('auth');

Route::get('/news-data', 'NewsController@data')->name('news_data')->middleware('auth');
Route::get('/task/marked/{id}', 'TaskController@logicDelete')->name('task_marked')->middleware('auth');
Route::get('/news/read/{id}', 'NewsController@readNews')->name('read_news')->middleware('auth');


Route::get('/admin/cards', 'CardController@index')->name('cards')->middleware('auth');
Route::get('/admin/card/new', 'CardController@create')->name('cards new')->middleware('auth');
Route::get('/admin/card/edit/{id}', 'CardController@edit')->name('card edit')->middleware('auth');
Route::post('/admin/cards/duplify', 'CardController@copy')->name('copycards')->middleware('auth');

Route::get('/admin/coupon', 'CouponController@index')->name('coupon')->middleware('auth');
Route::get('/admin/coupon/new', 'CouponController@create')->name('coupon new')->middleware('auth');
Route::get('/admin/coupon/edit/{id}', 'CouponController@edit')->name('coupon edit')->middleware('auth');
Route::post('/admin/coupon/duplify', 'CouponController@copy')->name('copycoupon')->middleware('auth');

Route::get('/autocomplete', 'ComuniController@autocomplete')->name('autocomplete')->middleware('auth');
Route::get('/autocomplete_ext', 'ComuniController@autocomplete_ext')->name('autocomplete_ext')->middleware('auth');
Route::post('/task/mail/', 'TaskController@sendMail')->name('send-mail')->middleware('auth');

Route::resource('preventivo', 'PreventivoController');
Route::resource('card', 'CardController');
Route::resource('coupon', 'CouponController');
Route::resource('customer', 'CustomerController');
Route::resource('customers', 'CustomersController');
Route::resource('customer_adv', 'AdvController');
Route::resource('newUser', 'newUserController');
Route::resource('uploads', 'uploadsController');
Route::resource('travel', 'TravelController');
Route::resource('tasks', 'TaskController');
Route::resource('news', 'NewsController');
Route::resource('file', 'FileController');
Route::resource('reparti', 'RepartiController');
Route::resource('business', 'BusinessController');

crm/app/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use SoftDeletes;
    use Notifiable;

    protected $table = 'users';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'surname'. 'username','email', 'password','admin',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

crm/resources/views/user/edit-news.blade.php
@extends('layouts.master')
@section('header-page-personalization')
    <style>
        #news_table thead,
        #news_table th {
            text-align: center;
        }

        #news_table tr {
            text-align: center;
        }

        .disabled {
            pointer-events: none;
            cursor: default;
        }
    </style>
@endsection
@section('content')
    <div class="page_content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <form id="login_form" role="form" method="POST" action="{{ route('news.store') }}">
                        {{ csrf_field() }}
                        <div class="panel panel-default">

                            <div class="panel-body">
                                <fieldset>
                                    <legend><span>Viaggio</span></legend>
                                </fieldset>
                                @if(session()->has('message'))
                                    <div class="alert alert-success">
                                        {{ session()->get('message') }}
                                    </div>
                                @endif
                                @if(session()->has('error'))
                                    <div class="alert alert-error">
                                        {{ session()->get('error') }}
                                    </div>
                                @endif
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            <label for="reg_input">Titolo News</label>
                                            <input type="text" id="news_title" name="news_title" class="form-control" value="{{$news->news_title}}">
                                        </div>
                                    </div>


                                             <?php 
                                                $error=false;
                                                $userid = Auth::user()->id;
                                                if($news->userid!=$userid)
                                                    $error=true;
                                                $zone=DB::select("SELECT userZone FROM `newsUserZone` WHERE userid='$userid'");
                                            if(empty($zone))
                                                $zone="Tutte le zone";
                                             else
                                                $zone=$zone[0]->userZone;
                                            ?>
                                        <input type="hidden" id="id" name="id" value="{{$news->id}}">
                                        <input type="hidden" id="zone" name="zone" value="{{$news->zone}}">
                                        <input type="hidden" id="userid" name="userid" value="{{$news->userid}}">

                                                                           
                                    <div class="col-lg-12">
                                        <div class="form-group pull-left">
                                            <label for="Evidenza" style="text-align: center;">
                                                News in evidenza
                                            </label>

                                            <input type="checkbox" class="form-control input-sm" name="evidenza_news" id="evidenza_news" 
                                                <?php if($news->evidenza==1)
                                                        echo "checked";
                                                ?>
                                            >
                                        </div>
                                    </div>
                                    <div class="col-lg-12">
                                        <div class="panel panel-default">
                                            <div class="panel-heading">Testo della news</div>
                                            <div class="panel_body_a">
                                            <textarea name="wysiwg_full" id="wysiwg_full" cols="30" rows="4"
                                                      class="form-control" value="{{$news->news_body}}">
                                                      {{$news->news_body}}

                                            </textarea>
                                            </div>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                        <button class="btn btn-lg btn-success btn-block">Modifica News</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
 
<script type="text/javascript">
    var error='<?php echo $error?>';
    if(eval(error))
        window.location.href="https://crm.suend.it/user/news";
</script>


@endsection
@section('footer-plugin')
    <!-- wysiwg editor -->
    <script src="{{ asset('/lib/ckeditor/ckeditor.js') }}"></script>
    <script src="{{ asset('/lib/ckeditor/adapters/jquery.js') }}"></script>
    <!-- wizard functions -->
    <script src="{{ asset('/js/apps/tisa_wysiwg.js') }}"></script>
    <!-- datatables -->
    <script src="{{ asset('/lib/DataTables/media/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('/lib/DataTables/media/js/dataTables.bootstrap.js') }}"></script>
    <script src="{{ asset('/lib/DataTables/extensions/TableTools/js/dataTables.tableTools.min.js') }}"></script>
    <script src="{{ asset('/lib/DataTables/extensions/Scroller/js/dataTables.scroller.min.js') }}"></script>

    <!-- datatables functions -->
    <script src="{{ asset('/js/apps/tisa_datatables.js') }}"></script>
@endsection

crm/resources/views/user/home.blade.php
@extends('layouts.master')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

crm/resources/views/user/new-user.blade.php
@extends('layouts.master')
@section('header-page-personalization')
    <style>
        .twitter-typeahead, .tt-hint, .tt-input, .tt-menu { width: 100%;  }
        .tt-menu {
            background: #ffffff;
        }
/*
fieldset {
  overflow: hidden
}

fieldset .some-class {
  float: left;
  clear: none;
}

fieldset label {
  float: left;
  clear: none;
  display: block;
  padding: 2px 1em 0 0;
}

fieldset input[type=radio],
fieldset input.radio {
  float: left;
  clear: none;
  margin: 2px 0 0 2px;
}*/

    </style>
@endsection
@section('content')
    <div class="page_content">

        <div class="container-fluid">
                           @if(session()->has('message'))
                                <div class="alert alert-success">
                                    {{ session()->get('message') }}
                                </div>
                            @endif         
            <div class="row">
                <div class="col-lg-12">
                  <form id="register_form" role="form" method="POST" action="{{ route('newUser.store') }}">
                      {{ csrf_field() }}
                      <h1 class="login_heading">Crea un Nuovo utente </span></h1>
                      <div class="form-group">
                          <label for="register_username">Nome</label>


                          <input type="text" class="form-control input-lg" name="name" id="name" value="{{ old('name') }}" required
                                 autofocus>
                          @if ($errors->has('name'))
                              <span class="help-block">
                                  <strong>{{ $errors->first('name') }}</strong>
                              </span>
                          @endif
                      </div>
                      <div class="form-group">
                          <label for="register_surname">Cognome</label>
                          <input type="text" class="form-control input-lg" id="surname" name="surname" value="{{ old('surname') }}" required>
                          @if ($errors->has('surname'))
                              <span class="help-block">
                              <strong>{{ $errors->first('surname') }}</strong>
                          </span>
                          @endif
                      </div>
                      <div class="form-group">
                          <label for="register_surname">Username</label>
                          <input type="text" class="form-control input-lg" id="username" name="username" value="{{ old('username') }}"
                                 required>
                          @if ($errors->has('username'))
                              <span class="help-block">
                              <strong>{{ $errors->first('username') }}</strong>
                          </span>
                          @endif
                      </div>
                      <div class="form-group">
                          <label for="register_email">Email</label>
                          <input type="text" class="form-control input-lg" id="email" name="email" value="{{ old('email') }}"
                                 required>
                          @if ($errors->has('email'))
                              <span class="help-block">
                                  <strong>{{ $errors->first('email') }}</strong>
                              </span>
                          @endif
                      </div>


                      <div class="form-group">
                          <label for="register_password">Password</label>
                          <input type="password" class="form-control input-lg" name="password" id="password" required>
                          @if ($errors->has('password'))
                              <span class="help-block">
                              <strong>{{ $errors->first('password') }}</strong>
                          </span>
                          @endif
                      </div>

                      <div class="form-group">
                          <label for="register_password">Conferma Password</label>

                          <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required>
                      </div>
                      <div class="form-group" style="display: none;">
                          <label for="register_password">Amministratore</label>
                          <input type="hidde" class="form-control input-sm" name="admin" id="admin" value="0">
                          @if ($errors->has('admin'))
                              <span class="help-block">
                              <strong>{{ $errors->first('admin') }}</strong>
                          </span>
                          @endif
                      </div>

                      <div class="submit_section">
                          <button type="submit" class="btn btn-lg btn-success btn-block">Salva</button>

                      </div>
                  </form>
                </div>

            </div>
        </div>
<?php 
  $IsSuperAdmin=true;
  $idutente=Auth::user()->id;
  if($idutente!=1)
    $IsSuperAdmin=false;
?>
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                        <div class="panel panel-default">

                            <div class="panel-body">
                                <fieldset>
                                    <legend><span>Utenti della piattaforma</span></legend>
                                    <p>Assegna le zone agli utenti della piattaforma</p>
                                </fieldset>
                                <div class="row">
                                    <div class="col-lg-12">
                                            <table class="table table-bordered" id="user_table" >
                                                <thead>
                                                <tr>
                                                    <th>Id</th>
                                                    <th>Cognome</th>
                                                    <th>Nome</th>
                                                    <th>Username</th>
                                                    <th>Email</th>
                                                    <th>Amministratore?</th>
                                                    <th>Zona</th>
                                                   <?php if($IsSuperAdmin){ ?>
                                                      <th>Permessi di visualizzazione</th>
                                                      <th>Elimina</th>
                                                    <?php } ?>
                                                    <th>Azione</th>
                                                </tr>
                                                </thead>
                                                <tbody>
<?php 
  if(Auth::user()->id==1)
    $sql = "SELECT users.id id,name,surname,username,email,admin,userZone, users.permessi FROM `users` LEFT JOIN newsUserZone ON users.id=userid";
  else
    $sql="SELECT users.id id,name,surname,username,email,admin,COALESCE(userZone,'Tutte le zone') userZone FROM `users` LEFT JOIN newsUserZone ON users.id=userid WHERE userZone IS NULL OR userZone in (SELECT userZone FROM newsUserZone WHERE userid='$idutente')";
     $query = DB::select($sql);
  
  $zone=DB::select("SELECT * FROM `newsZone`");
  for($i=0;$i<count($query);$i++){?>
<tr>
  <td>{{$query[$i]->id}}</td>
  <td>{{$query[$i]->surname}}</td>
  <td>{{$query[$i]->name}}</td>
  <td>{{$query[$i]->username}}</td>
  <td>{{$query[$i]->email}}</td>
   <td>
    <?php if($IsSuperAdmin){ ?>
      <select name="admin" class="form-control" onchange="updateAdmin(this)">
        <option value="1" <?php if($query[$i]->admin==1) echo "selected"; ?>>Si </option>
        <option value="0" <?php if($query[$i]->admin==0) echo "selected"; ?>> No </option>
      </select>
    <?php }else{ ?>
      <?php if($query[$i]->admin==1) echo "Si"; ?>
      <?php if($query[$i]->admin==0) echo "No"; ?>
    <?php } ?>
  </td>
  <td>




<?php if(empty($query[$i]->userZone)) { ?>
      <select name="zone" class="form-control" onchange="updateZone(this)">
        <option disabled selected>Scegli una zona</option>
        <?php 

         for($j=0;$j<count($zone);$j++){?>
        <option value="{{$zone[$j]->zone}}">{{$zone[$j]->zone}}</option>
        <?php } ?>
      </select>

    <?php }else{ ?>

      <select name="zone" class="form-control" onchange="updateZone(this)">
        <?php 
        for($j=0;$j<count($zone);$j++){?>
        <option value="{{$zone[$j]->zone}}"<?php 
        if($zone[$j]->zone==$query[$i]->userZone)
          echo "selected";?>
        >{{$zone[$j]->zone}}</option>
        <?php } ?>
      </select>
    <?php } ?>
    
  </td>

  <?php if($IsSuperAdmin){ ?>
    <td>
      <form>
        <fieldset>
          <div class="some-class">
            <input type="radio" onclick="changePermissionLevel({{$query[$i]->id}},1)" class="radio" name="Permessi" value="1" id="y" <?php if($query[$i]->permessi=="1") echo 'checked="checked"';?> />
            <label for="y">Puo visualizzare tutto</label>

            <input type="radio" onclick="changePermissionLevel({{$query[$i]->id}},0)" style="clear:both;" class="radio" name="Permessi" value="0" <?php if($query[$i]->permessi=="0") echo 'checked="checked"';?> id="z" />
            <label for="z">Puo visualizzare solo ciò che inserisce</label>
          </div>
        </fieldset>
      </form>
    </td>
   <td><a href="#" class="btn btn-xs btn-danger news-zama" style="margin-left: 10px;" onclick="deleteRecord(this)"><i class="glyphicon glyphicon-minus" class="disabled"></i>&nbsp;Elimina</a></td>
  <?php } ?>
  <td><a href="../admin/newUser/{{$query[$i]->id}}" class="btn btn-xs btn-secondary"><i class="glyphicon glyphicon-edit"></i>&nbsp;Modifica</a></td>
</tr>
<?php } ?>
                                                </tbody>
                                            </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                </div>
            </div>
        </div>

    </div>
@endsection
@section('footer-plugin')
<script type="text/javascript">
window['table']="users";

function changePermissionLevel(userid,lv) {
  debugger;

  $.ajax({
        url: '../api.php',     
        type: "POST",
        data: { 
            qr:'changePermissionLevel',
            userid:userid,
            lv:lv,
          },
      success: function(res){
          debugger;
    },
    error: function(){
          debugger;
    }
    });  
}

function updateZone(el) {

var userid=$(el).parents('tr').find('td:eq(0)').text().trim();
var userZone=$(el).find('option:selected').val();

$.ajax({
      url: '../api.php',     
      type: "POST",
      data: { 
          qr:'updateZone',
          userid:userid,
          userZone:userZone,
        },
    success: function(res){
      
  console.log(res);
  },
  error: function(){
      
    console.log("ajax error ");
  }
  });  
}
function updateAdmin(el) {

var userid=$(el).parents('tr').find('td:eq(0)').text().trim();
var status=$(el).find('option:selected').val();

$.ajax({
      url: '../api.php',     
      type: "POST",
      data: { 
          qr:'updateAdmin',
          userid:userid,
          status:status,
        },
    success: function(res){
      
  console.log(res);
  },
  error: function(){
      
    console.log("ajax error ");
  }
  });  
}

</script>
@endsection